# Site settings
author: Dwayne Weller
title: Dwayne Weller
header-img: images/home-bg.png # CHANCE TO NAME BANNER
email: dpweller85@gmail.com
copyright_name: Dwayne Weller
description: > # this means to ignore newlines until "baseurl:"
  I am a Full Stack Web Developer expanding my knowledge in Ruby on Rails, JavaScript, React.js, and Python.
  Seeking to serve and collaborate with a team who aligns with my values. I believe technology is a platform to 
  improve lives and empower growth. I look forward to collaborating with others to serve that cause.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Dwaynew85

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
